services:
  - type: worker
    name: reddit-scraper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.services.reddit_service"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: USER_AGENT
        sync: false